name: ${project.name}
version: ${project.version}
description: ${project.description}
website: ${project.url}
author: totemo
authors: [totemo, Dumbo52]
depend: [ProtocolLib]
main: nu.nerd.nerdmoods.NerdMoods

permissions:
    nerdmoods.admin:
        description: Permission to administer the plugin (run /nerdmoods reload).
        default: op

commands:
    nerdmoods:
        description: Administration command for NerdMoods.
        permission: nerdmoods.admin
        usage: |
            /<command> help|reload
    prain:
        description: Turns client-side weather on or off. Omit the argument to synchronise weather with the server.
        usage: |
            /<command> [on|off]
    ptime:
        description: Sets the player's client-side time. If using a number, the given time should be between 0 and 24000. Omit the argument to synchronise time with the server.
        usage: |
            /<command> [day|night|<time>]
